# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4886320f9997b8fc951ce082496fcefbef92431d6922899495899b372a2ffbb2995822f5f1962ec75ec6c55642416020ed987bac24b674de18fcbdaabede7230

test:
  secret_key_base: 3a574832824d199115c33609d2493a3922fa5ecb4e6a484246b54cde061a593c9a636b26b6f724ef98299556b4462e585776a065c6588d74ecc0a4b3807fda60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
